### PR TITLE
Feature/display all users fix

### PR DESCRIPTION
**Pull request by mtomasic2**
Implemented a feature to ensure that when a user is deleted, all associated data is seamlessly removed as well. This enhancement contributes to a more thorough and streamlined user management system by automatically handling the deletion of related data, including reservations and notifications.

### CODE REVIEW

**Review by iplavsic20 — APPROVED** [review]
Good fix :)

**Review by dsantek20 — APPROVED** [review]
Nice

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by ijelovic20 — APPROVED** [review]
Good fix

**Pull request merged**
