### PR TITLE
Test/admin home page

### PR DESCRIPTION
**Pull request by iplavsic20**
Test for admin home page display. Widget tests to verify the rendering of main title, display of profile icon, presence of buttons, and proper navigation in AdminHomePage.

### CODE REVIEW

**Review by mtomasic2 — APPROVED** [review]
Nice tests.

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by ijelovic20 — APPROVED** [review]
Good!

**Review by dsantek20 — APPROVED** [review]
Good

**Pull request merged**
