### PR TITLE
TIDIJ-235 Created tests vehicle management

### PR DESCRIPTION
**Pull request by dsantek20**
Created tests for vehicle management

### CODE REVIEW

**Review by iplavsic20 — APPROVED** [review]
Good job

**Review by jsmoljanec — APPROVED** [review]

**Review by jsmoljanec — APPROVED** [review]
👍

**Review by mtomasic2 — APPROVED** [review]
Nice tests.

**Review by ijelovic20 — APPROVED** [review]
Good!

**Pull request merged**
