### PR TITLE
Feature/notify me logic fix

### PR DESCRIPTION
**Pull request by iplavsic20**
Fixed to review reservations if the date within notifyme is after the reservation cancellation date. Additionally, fixed the review for the time if the date is the same as the reservation date and the end date in notifyme.

### CODE REVIEW

**Review by dsantek20 — APPROVED** [review]
Good fix

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by mtomasic2 — APPROVED** [review]
Good fix

**Review by ijelovic20 — APPROVED** [review]
Good fix

**Pull request merged**
