### PR TITLE
Feature/all reservations for administrator

### PR DESCRIPTION
**Pull request by iplavsic20**
Implemented display of all reservations, including the first and last names of the users who made the reservations, and deletion of reservations.

### CODE REVIEW

**Review by mtomasic2 — APPROVED** [review]
Good job on implementing all resevations page for admin.

**Review by ijelovic20 — APPROVED** [review]
Great

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by dsantek20 — APPROVED** [review]
Good job

**Pull request merged**
