### PR TITLE
Feature/reservations UI fix

### PR DESCRIPTION
**Pull request by ijelovic20**
Fixed ui for reservations page for user and administrator. Past reservations can not be canceled. Past reservations are presented in another color.

### CODE REVIEW

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by mtomasic2 — APPROVED** [review]
Nice fix.

**Review by dsantek20 — APPROVED** [review]
Good fix!

**Review by iplavsic20 — APPROVED** [review]
Good fix

**Pull request merged**
