### PR TITLE
Feature/profile picture

### PR DESCRIPTION
**Pull request by jsmoljanec**
Profile picture functionality has been successfully implemented.
Users now have the option for adding their own profile picture.

### CODE REVIEW

**Review by iplavsic20 — APPROVED** [review]
Great job

**Review by ijelovic20 — APPROVED** [review]
Great

**Review by mtomasic2 — APPROVED** [review]
Good job on implementing functionality of changing profile picture.

**Review by dsantek20 — APPROVED** [review]
Good code

**Pull request merged**
