### PR TITLE
TIDIJ-183 Added remember admin user and loading screen

### PR DESCRIPTION
**Pull request by jsmoljanec**
Fixed login with admin. The error was that when starting the application, the page for the employee opens to the administrator.

### CODE REVIEW

**Review by iplavsic20 — APPROVED** [review]
Great fix for remembering logged employee and admin

**Review by mtomasic2 — APPROVED** [review]
Very important fix, good job. :)

**Review by dsantek20 — APPROVED** [review]
Good fix

**Review by ijelovic20 — APPROVED** [review]
Important thing fixed 👍

**Pull request merged**
