### PR TITLE
Feature/my reservations

### PR DESCRIPTION
**Pull request by ijelovic20**
Implemented feature for users to see all their reservations. Reservations are sorted by date. Users also can cancel their reservation, but not ones that are not available anymore.

### CODE REVIEW

**Review by mtomasic2 — APPROVED** [review]
Well done.

**Review by iplavsic20 — APPROVED** [review]
Good job :)

**Review by jsmoljanec — APPROVED** [review]
Impressive work 👍

**Review by dsantek20 — APPROVED** [review]
Good job

**Pull request merged**
