### PR TITLE
TIDIJ-236 Tests for getCarDetails.  Covering retrieval and verificati…

### PR DESCRIPTION
**Pull request by iplavsic20**
Tests for getCarDetails. Covering retrieval and verification of vehicle details, handling non-existing vehicles, and throwing exceptions for null vinCar to ensure robustness and correctness.

### CODE REVIEW

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by ijelovic20 — APPROVED** [review]
Good!

**Review by mtomasic2 — APPROVED** [review]
Good job.

**Review by mtomasic2 — APPROVED** [review]
Good job.

**Review by dsantek20 — APPROVED** [review]
Good job

**Pull request merged**
