### PR TITLE
Feature/vehicle simulation optimization

### PR DESCRIPTION
**Pull request by mtomasic2**
This pull request focuses on code enhancements, organization, and overall optimization. I have refactored the code, reducing the load on several classes by extracting methods and improving overall structure. These changes aim to enhance code readability, maintainability, and performance.

### CODE REVIEW

**Review by ijelovic20 — APPROVED** [review]
Great!

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by dsantek20 — APPROVED** [review]
Very nice

**Review by iplavsic20 — APPROVED** [review]
Good job

**Pull request merged**
