### PR TITLE
Feature/display all users

### PR DESCRIPTION
**Pull request by mtomasic2**
Display of all users for admin has been successfully implemented. 
Admin now has the ability to seamlessly delete users directly from the interface.
Introduced a search feature allowing the admin to efficiently find users based on their first and last names.

### CODE REVIEW

**Review by ijelovic20 — APPROVED** [review]
Great!

**Review by dsantek20 — APPROVED** [review]
Good

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by iplavsic20 — APPROVED** [review]
Good job :)

**Pull request merged**
