### PR TITLE
TIDIJ-217 Fixed call to the function that reviews the NotifyMe table …

### PR DESCRIPTION
**Pull request by iplavsic20**
Fixed call to the function that reviews the NotifyMe table when canceling a reservation, and if there is a matching NotifyMe entry, store the data in the Notifications table.

### CODE REVIEW

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by dsantek20 — APPROVED** [review]
Good fix

**Review by mtomasic2 — APPROVED** [review]
Good fix.

**Review by ijelovic20 — APPROVED** [review]
Good fix!

**Pull request merged**
