### PR TITLE
TIDIJ-115 Feature/ci cd

### PR DESCRIPTION
**Pull request by jsmoljanec**
The build_upload CI/CD system is designed to automatically trigger upon each push to the develop branch. Its main objective is to build and store Flutter application on Google Drive for project fleetcarpooling.

### CODE REVIEW

**Review by iplavsic20 — APPROVED** [review]
Good job :)

**Review by mtomasic2 — APPROVED** [review]
Good job.

**Review by ijelovic20 — APPROVED** [review]
Great

**Review by dsantek20 — APPROVED** [review]
Very good

**Pull request merged**
