### PR TITLE
TIDIJ-237 Added dialog with user data

### PR DESCRIPTION
**Pull request by dsantek20**
Added a dialogue with user data: picture, activity status, first name, last name, e-mail address and role.

### CODE REVIEW

**Review by jsmoljanec — APPROVED** [review]
Good job!

**Review by iplavsic20 — APPROVED** [review]
Great job :)

**Review by mtomasic2 — APPROVED** [review]
Good job.

**Review by ijelovic20 — APPROVED** [review]
Good!

**Pull request merged**
