### PR TITLE
Feature/file names and warnings fix

### PR DESCRIPTION
**Pull request by mtomasic2**
Refactored file names, organized folder structure, and addressed warnings for improved codebase cleanliness and maintainability.

### CODE REVIEW

**Review by jsmoljanec — APPROVED** [review]
Nice job!

**Review by dsantek20 — APPROVED** [review]
Very nice

**Review by iplavsic20 — APPROVED** [review]
Great job :)

**Review by ijelovic20 — APPROVED** [review]
Nice!

**Pull request merged**
