### PR TITLE
Feature/car details for admin

### PR DESCRIPTION
**Pull request by ijelovic20**
Implemented displaying vehicle's informations for administrator. Administrator also can activate/deactivate and delete selected vehicle.

### CODE REVIEW

**Review by dsantek20 — APPROVED** [review]
Great job

**Review by mtomasic2 — APPROVED** [review]
Good job.

**Review by iplavsic20 — APPROVED** [review]
Good job on implementation of car details for admin :)

**Review by jsmoljanec — APPROVED** [review]
Nice work!

**Pull request merged**
